-added basic single command symfony/console implementation
Idrinth/phpunit-test-generator pull request #20
Opened 2018-04-07 18:57 UTC by JEM94

2018-04-07 18:58 UTC, JEM94 commented on bin/generate-tests.php
> +(new Application('echo', '1.0.0'))
schon gesehen :D

2018-04-07 19:12 UTC, Idrinth requested changes

2018-04-07 19:12 UTC, Idrinth commented on composer.json
> +        "symfony/console":"^4.0.0",
4.0.0 is not going to work on php 5.3

2018-04-07 19:12 UTC, Idrinth commented on bin/generate-tests.php
> +    ->register('generate-tests')
please register a command class, so that this file here has as little logic as possible.

2018-04-07 22:27 UTC, Idrinth commented
Just to give a reason for why I'd like the command to be a class(extending symfony's command class):
- it's hard to test procedural code automatically
- Once #9 is going to happen, we'd need to put even more untestable logic in the procedural code
- it is very likely, that the complexity of the command will increase, making tests more important

On a technical basis the implementation looks ok, the main issue is how hard it's going to be to test it.

2018-04-08 11:35 UTC, Idrinth commented on bin/generate-tests.php
> +    ->register('generate-tests')
and add defaults

2018-05-05 18:00 UTC, Idrinth commented
@JEM94 should we close this and delete the branch? we're waiting on idrinth/simple-console#2 after all

2018-07-11 07:12 UTC, closed without merging